### ISSUE TITLE
Question about themes

### ISSUE THREAD

**Issue by Limones-07** [JezerM/sea-greeter#1]
It isn't an issue, it's a question. 
I'm searching for alternatives for webkit2-greeter, found this one, but I didn't found any themes on the web (💀) so, can we use webkit2-greeter themes on this greeter?

**Comment by JezerM** [comment]
Yeah, you can use existing webkit2-greeter in sea-greeter, as well as in web-greeter and nody-greeter. However, lots of these themes are using a deprecated API by lightdm-webkit2-greeter which is currently removed by this greeter, so they may not work.

Though, you can see [web-greeter-page](https://github.com/JezerM/web-greeter-page), or here: https://jezerm.github.io/web-greeter-page/themes, where I collect all themes that currently works with my own web based greeters. There may be other themes that could work but that I have not seen~

If a theme doesn't work, you can either submit an issue to their author to fix it or submit an issue to web-greeter-page so I could try to fix it by myself :D

**Comment by Limones-07** [comment]
> Yeah, you can use existing webkit2-greeter in sea-greeter, as well as in web-greeter and nody-greeter. However, lots of these themes are using a deprecated API by lightdm-webkit2-greeter which is currently removed by this greeter, so they may not work.
> 
> Though, you can see [web-greeter-page](https://github.com/JezerM/web-greeter-page), or here: https://jezerm.github.io/web-greeter-page/themes, where I collect all themes that currently works with my own web based greeters. There may be other themes that could work but that I have not seen~
> 
> If a theme doesn't work, you can either submit an issue to their author to fix it or submit an issue to web-greeter-page so I could try to fix it by myself :D

Thank you! I'm about to install it then :)

**Comment by Limones-07** [comment]
Yo, another question.
On the lightdm.conf file, what should be the greeter-session value?

**Comment by JezerM** [comment]
The name of the greeter:

- If using web-greeter, then set `greeter-session=web-greeter`
- If using nody-greeter, set `greeter-session=nody-greeter`
- If using sea-greeter, set `greeter-session=sea-greeter`

**Comment by Limones-07** [comment]
Hey! Sorry for the annoyance, but I have another problem. 
The Litarvan theme that is in your website (this one: https://github.com/Litarvan/lightdm-webkit-theme-litarvan) isn't working, neither with nody-greeter or sea-greeter. 
On nody-greeter, it pops up an error message saying about a TypeError: lightdm.language.toLowerCase isn't a function on chunk base js file (coudn't take a screenshot). 
On sea-greeter, it just enters on a loop, with the blinking cursor on the top of the screen and black to gray-ish screen, like it's about to load the theme. To get out, I need to power off the computer and use the kernel parameters to boot with multi-user.target, so I can go back to light-gtk-greeter.
I coudn't find any log files (I don't even know where to search lol). If you can help, I would appreciate it so much!

**Comment by JezerM** [comment]
Are you using the 3.2.0 release or the master version? Only the master version works with web-greeter, nody-greeter and sea-greeter, as I made some fixes after the 3.2.0 release was made.

**Comment by JezerM** [comment]
Also, you can find the logs at `/var/log/lightdm/`. The `seat0-greeter.log` file contains the greeter log, whether it is lightdm-gtk-greeter or sea-greeter.

**Comment by Limones-07** [comment]
> Are you using the 3.2.0 release or the master version? Only the master version works with web-greeter, nody-greeter and sea-greeter, as I made some fixes after the 3.2.0 release was made.

I'm not really sure... I'm cloning and building it again, with the master branch selected, so I can test.


> Also, you can find the logs at `/var/log/lightdm/`. The `seat0-greeter.log` file contains the greeter log, whether it is lightdm-gtk-greeter or sea-greeter.

Sea-greeter log file: http://0x0.st/o4m5.txt

**Comment by Limones-07** [comment]
Update: It worked. With two errors, but it worked, I was able to log in.
This time I took photos, as I don't have scrot running on LightDM.
The first error was right when it loaded: 
![a](https://user-images.githubusercontent.com/89426080/192914084-28439d45-d81d-4930-8b89-340a5e46cc8b.jpeg)
"An error ocurred. Do you want to change to default theme? (gruvbox)
file:///usr/share/web-greeter/themes/litarvan/img/background.b9890328.png O: Failed to load resource: Error opening file /usr/share/web-greeter/themes/litarvan/img/background.b9890328.png: No such file or directory." 

Second error:
![b](https://user-images.githubusercontent.com/89426080/192914451-15ee59b0-1455-41b1-a1b5-fd3565857364.jpeg)
"An error ocurred. Do you want to change to default theme? (gruvbox)
file:///home/limones/.face O: Failed to load resource: Error opening file: /home/limones/.face: Permission denied." 
I don't have a .face file...

I'm gonna try to see what's going on and I'm going to tell you about anything that happens.

**Comment by JezerM** [comment]
Nice!

The first error shows that Litarvan theme tried to load a background image, but it wasn't loaded. Perhaps, it was not copied when installing, or it is an error in Litarvan themes' code. I'd suggest to ignore it and select another background.

The second one is common. It is due permissions as the error says, the `lightdm` user simply doesn't own the `.face` file neither they have the permission to open it. So, I'd recommend to put your image file at `/var/lib/AccountsService/icons/$USER.png` and edit your accounts-service file at `/var/lib/AccountsService/users/$USER` to set your icon. You can see more about it at https://wiki.archlinux.org/title/LightDM#Changing_your_avatar

**Comment by Limones-07** [comment]
> Nice!
> 
> The first error shows that Litarvan theme tried to load a background image, but it wasn't loaded. Perhaps, it was not copied when installing, or it is an error in Litarvan themes' code. I'd suggest to ignore it and select another background.
> 
> The second one is common. It is due permissions as the error says, the `lightdm` user simply doesn't own the `.face` file neither they have the permission to open it. So, I'd recommend to put your image file at `/var/lib/AccountsService/icons/$USER.png` and edit your accounts-service file at `/var/lib/AccountsService/users/$USER` to set your icon. You can see more about it at https://wiki.archlinux.org/title/LightDM#Changing_your_avatar

It worked!! Thank you very much, JezerM!! 
Good luck on the sea-greeter development. :)
