### ISSUE TITLE
Litarvan can not go back to previsou page

### ISSUE THREAD

**Issue by ZaynChen** [JezerM/sea-greeter#2]
I am using `sea-greeter` and `litarvan`. However, after go to `setup` or `theming` page, I can not go back to the previous page, click on the `back` button dose not work. So, I have to `reload` the theme. As a result, after changing the settings, I have to click the `back` button to save, and then reload the theme to make it work as it only saves the settings but does not go back. The theme is working using `lightdm-webkit2-greeter`. In debug mode of `sea-greeter`, the `back`, `forward` and `stop` are disabled, only `reload` and `inspect element` is enabled. However, in `webkit2-greeter`, they are enabled. So, this issue is due to `sea-greeter` or theme `litarvan`? How can I fix this?

**Comment by JezerM** [comment]
Are you using the 3.2.0 version or the master branch of Litarvan? The 3.2.0 isn't updated for sea-greeter, so the master version is recommended.

**Comment by ZaynChen** [comment]
Yes, I am using the master branch of Litarvan, not the 3.2.0 release version. I use ./build.sh to generate the theme, and manually install it to my archlinux. I add console.log() around `this.$router.back()` in [PowerButton.vue](https://github.com/Litarvan/lightdm-webkit-theme-litarvan/blob/master/src/components/PowerButton.vue) of litarvan, the click events seems working as the console outputs in devtools are expected, so `this.$router.back()` seems not working.

**Comment by JezerM** [comment]
Hmm, I'll look into that.

**Comment by ZaynChen** [comment]
I add `console.log(history)` around `this.$router.back()`, `this.$router.push()`, ..., the length of the history is always 1 and never changes. When I switch to `webkit2-greeter`, the length will increase when I go to settings and theming pages, and it can go back or forward correctly. So maybe this issue is related to the `history`.

**Comment by JezerM** [comment]
Looks like it's a sea-greeter bug. As you say, the history length is always 0 in Vue.js based themes like **Litarvan** or my **lightdm-void-theme**. I thought it was fixed back then... I'll look for a solution.

**Comment by JezerM** [comment]
Fixed in 6387cd8aca49b2503f7607edac30a56661c2921e :D
